- name: create ec2 launch config
  hosts: localhost
  connection: local
  tasks:
  - name: ec2 lc create
    ec2_lc:
      name: "{{ launch_config }}"
      image_id: ami-a9d09ed1
      instance_type: t2.micro
      key_name: ansible-test
      security_group: default
      region: us-east-1
      user_data_path: /home/ansible/user_data

